### ISSUE TITLE
Duplicate classes when used with other player

### ISSUE THREAD

**Issue by SystemBlad** [doublesymmetry/KotlinAudio#17]
Hi, thanks for this great library.
I am working in a project that uses a old exoplayer dependencie and I having these kind of errors:

```
 Duplicate class com.google.android.exoplayer2.ui.WebViewSubtitleOutput$1 found in modules jetified-exoplayer-ui-2.14.2-runtime (com.google.android.exoplayer:exoplayer-ui:2.14.2) and jetified-exoplayer-ui-r2.16.4-runtime (com.github.DoubleSymmetry.ExoPlayer:exoplayer-ui:r2.16.4)

 Duplicate class com.google.android.exoplayer2.video.spherical.CameraMotionListener found in modules jetified-exoplayer-core-2.14.2-runtime (com.google.android.exoplayer:exoplayer-core:2.14.2) and jetified-exoplayer-core-r2.16.4-runtime (com.github.DoubleSymmetry.ExoPlayer:exoplayer-core:r2.16.4)
```

It is because Kotlin audio is using the same "com.google.android.exoplayer2" package name, maybe could be it changed for future versions?

**Comment by Robiullah2244** [comment]
Any update?

**Comment by mpivchev** [comment]
We are currently planning to stop using our fork of ExoPlayer, so this should potentially fix this issue.

**Comment by dcvz** [comment]
Fork was removed some while back and should have resolved this issue
