### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by austinried** [doublesymmetry/KotlinAudio#19]
Looks like this project is missing a license, and since it's a dependency of react-native-track-player and I include licenses in my build, and fail the build when licenses are missing (or not manually added, but I can't find one here to add), my build is broken with the Android rewrite.  Could you add a license to this library?  Thank you!

**Comment by dcvz** [comment]
@austinried LICENSE had been added!

**Comment by austinried** [comment]
Thank you!
