### ISSUE TITLE
AOD breaks remote seek 

### ISSUE THREAD

**Issue by jspizziri** [doublesymmetry/KotlinAudio#27]
I've done some testing and this commit has broken remote seek:

https://github.com/doublesymmetry/KotlinAudio/commit/ed216af2dd72b500b66c82f3239777d1129844bb

Note sure why, I'll look into it but if anyone has any ideas that'd be great.

**Comment by mpivchev** [comment]
Closed as this is already fixed

**Comment by mpivchev** [comment]
@jspizziri any update on this, or is it still a TODO?
