### ISSUE TITLE
Generate 1.2.5

### ISSUE THREAD

**Issue by arthurgeron-work** [doublesymmetry/KotlinAudio#56]
[This](https://github.com/doublesymmetry/KotlinAudio/commit/dd4bdab147c90fffcff7800790dbfcb41291d29b) commit fixes a crash related to react-native fast reloads, but the latest commit breaks react-native-track-player if KotlinAudio is used on main, can the maintainers/owners please generate a tag 1.2.5 with the mentioned commit?

**Comment by bradleyflood** [comment]
Assuming this will be fixed in V2 @arthurgeron-work ?

**Comment by arthurgeron-work** [comment]
It does look like v 2.0.0rc6 is [compatible](https://github.com/doublesymmetry/react-native-track-player/blob/d85262c113e2aa163ff8870a3074bd07a4850a8e/android/build.gradle#LL52C7-L52C69) with the latest react-native-track-player
