### ISSUE TITLE
KotlinAudio v1.1.0 is not available on jitpack

### ISSUE THREAD

**Issue by cancit** [doublesymmetry/KotlinAudio#73]
Hello, our builds started failing today because KotlinAudio v1.1.0 is not available in jitpack anymore. Is there a mitigation for this issue?
```
 > Failed to transform KotlinAudio-v1.1.0.aar (com.github.DoubleSymmetry:KotlinAudio:v1.1.0) to match attributes {artifactType=android-symbol-with-package-name, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find KotlinAudio-v1.1.0.jar (com.github.DoubleSymmetry:KotlinAudio:v1.1.0).
        Searched in the following locations:
            https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/v1.1.0/KotlinAudio-v1.1.0.aar
            https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/v1.1.0/KotlinAudio-v1.1.0.jar
```
When I checked the website, I see an error as well  https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/v1.1.0/
but for example 1.2.4 is available there  https://www.jitpack.io/com/github/DoubleSymmetry/KotlinAudio/v1.2.4/

**Comment by Xanewok** [comment]
Our fix was to fallback on the scijava repository for KotlinAudio v1.0.0

```gradle
maven { url 'https://maven.scijava.org/content/repositories/public' }
```

**Comment by xenokratos** [comment]
Rebuilding the package on jitpack did the trick see #74

**Comment by jspizziri** [comment]
@xenokratos thanks!

@dcvz I believe this issue can be closed.
