### ISSUE TITLE
Failing To Update LockScreen Meta Data

### ISSUE THREAD

**Issue by Tr736** [doublesymmetry/KotlinAudio#76]
Currently seeing an issue where i cannot update the image for the lock screen

I can see that the passed info i.e we have a title, artis and artwork but nothing seems to update on the lockscreen.

I have tried setting   player.automaticallyUpdateNotificationMetadata to both true and false

```
    @MainThread
    fun updateNotificationMetadata(title: String?, artist: String?, artwork: String?) {
        player.notificationManager.notificationMetadata = NotificationMetadata(title, artist, artwork)
    }
```

Please could you advise or help?

**Comment by lovegaoshi** [comment]
hi, i wonder if https://github.com/lovegaoshi/KotlinAudio/commit/7a3d90b5b7b548e45b8b54ffcf62eac5c795bc14 will help on this?

**Comment by Tr736** [comment]
i managed to fix this thanks
