### ISSUE TITLE
Another SimpleCache instance uses the folder 

### ISSUE THREAD

**Issue by malikoum94** [DoubleSymmetry/KotlinAudio#9]
Hi,

We are facing a cache issue with react-native-trackplayer it's seem the cache not being released before init a new player.

Have you any advice too avoid this?

https://github.com/DoubleSymmetry/KotlinAudio/blob/f06133fa589adabcd20929823af2a33245d9bc77/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/players/BaseAudioPlayer.kt#L112

**Comment by malikoum94** [comment]
sorry was soon previous build

**Comment by CDBridger** [comment]
i'm actually still getting this issue from trackplayer on v3.0 (and previous versions)

**Comment by mvrty** [comment]
Exoplayer seem to use the same cache folder and this is causing crashes on bundle reload in react-native-track-player

I assume a simple fix would be to change the cache-dir? 

https://github.com/DoubleSymmetry/KotlinAudio/blob/f06133fa589adabcd20929823af2a33245d9bc77/kotlin-audio/src/main/java/com/doublesymmetry/kotlinaudio/players/BaseAudioPlayer.kt#L110

**Comment by jspizziri** [comment]
@mpivchev @dcvz this seems like it might be something to look into.

**Comment by jspizziri** [comment]
@mvrty it looks like a recent commit added the ability to specify the cache identifier

https://github.com/doublesymmetry/KotlinAudio/pull/44/files#diff-f9d58e613b33bfae6ccd310bf54e0fc997a0662df63d6659d1a126ef0c870884R15

It hasn't been released yet, but I'm going to try and test locally to see if this resolves the issue we're seeing in RNTP, as you mentioned.

**Comment by jspizziri** [comment]
It definitely happens on a hot reload of RNTP, which is annoying more than anything probably. I'm suspicious it might be happening in other contexts (someone mentioned the possibility of it happening on app upgrade).

I also think it might be happening in multiple exoplayer installs too.

In short, I don't have great data on it right now. But there's a lot of activity about this and a lateinit issue over on RNTP.

**Comment by rborn** [comment]
@jspizziri 

It seems that SimpleCache has a `isCacheFolderLocked` method, so maybe it would be possible to make a singleton in case it already exist? 

https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/SimpleCache.html#isCacheFolderLocked(java.io.File)
